set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

" Assorted Golang Vim plugins.
Plugin 'fatih/vim-go'

Plugin 'editorconfig/editorconfig-vim'

" Syntax checking & linting.
"Plugin 'scrooloose/syntastic'
"let g:syntastic_javascript_checkers = ['jsxhint']
"let g:syntastic_aggregate_errors = 1

Plugin 'maksimr/vim-jsbeautify'
Plugin 'mxw/vim-jsx'
Plugin 'uarun/vim-protobuf'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'Matt-Deacalion/vim-systemd-syntax'
Plugin 'tpope/vim-fugitive'

call vundle#end()
filetype plugin indent on

" End Vundle-required stuff.

syntax enable
set t_Co=256
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

set mouse=a
set hlsearch
set incsearch
set ruler
set nobackup
set noswapfile

set colorcolumn=80

map N :cprev<CR>
map M :cnext<CR>

set completeopt=longest,menuone,preview

highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

" TODO(johnny): Move to cpp ftplugin.
" Switch between source and header
map <F5> :e %:r.h<CR>
map <F6> :e %:r.cc<CR>
nmap v<F5> :vsp<CR><C-W>h:e %:r.h<CR>
nmap v<F6> :vsp<CR><C-W>l:e %:r.cc<CR>

