set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/Vundle.vim'

Bundle 'nsf/gocode', {'rtp': 'vim/'}
"Bundle 'jnwhiteh/vim-golang'

"Bundle 'maksimr/vim-jsbeautify'
"Bundle 'walm/jshint.vim'

"Bundle 'Tagbar'

filetype plugin indent on
syntax enable

set t_Co=256
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

set mouse=a
set hlsearch
set incsearch
set ruler

map N :cprev<CR>
map M :cnext<CR>

set completeopt=longest,menuone

highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$/

let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
    \ }

